Move all the feature to hooks/command

diff --git a/hooks/command b/hooks/command
--- a/hooks/command
+++ b/hooks/command
@@ -2,8 +2,10 @@
 
 set -euo pipefail
 
+# common
+
 dotnet=${BUILDKITE_PLUGIN_GITHUB_BUMP_VERSION_RELEASE_DOTNET:-dotnet}
-github_release=${BUILDKITE_PLUGIN_GITHUB_BUMP_VERSION_RELEASE_RELEASE:-github-release}
+#github_release=${BUILDKITE_PLUGIN_GITHUB_BUMP_VERSION_RELEASE_RELEASE:-github-release}
 buildkite_agent=${BUILDKITE_PLUGIN_GITHUB_BUMP_VERSION_RELEASE_AGENT:-buildkite-agent}
 
 image="dxdx/docker-builder-dotnet:2.2"
@@ -11,9 +13,7 @@ image=${BUILDKITE_PLUGIN_GITHUB_BUMP_VERSION_RELEASE_IMAGE:-$image}
 
 debug=${BUILDKITE_PLUGIN_GITHUB_BUMP_VERSION_RELEASE_DEBUG:-0}
 if [ $debug -gt 0 ]; then
-    #whereis docker
     env
-    #docker-compose version
     docker version
     docker ps    
     whoami
@@ -22,14 +22,44 @@ fi
 
 docker=${BUILDKITE_PLUGIN_GITHUB_BUMP_VERSION_RELEASE_DOCKER:-docker}
 
+# version
+
 version="v0.0.0"
 dotnet_args="--rm -it $image /gitversion/GitVersion.dll /output json /nofetch /showvariable semVer"
 version=$($docker run -v $(pwd):/src -w /src --entrypoint dotnet $dotnet_args)
 
-$buildkite_agent meta-data set version $version
-$buildkite_agent annotate --style info "Using [$image] with GitVersion and SemVer"
-$buildkite_agent annotate --style success "Bump to version ${version}"
+if [ "$version" = "" ]; then
+    $buildkite_agent meta-data set version $version
+    $buildkite_agent annotate --style info "Using [$image] with GitVersion and SemVer"
+    $buildkite_agent annotate --style success "Bump to version ${version}"
 
-export VERSION=$version
+    export VERSION=$version
 
-echo $version
+    echo $version
+else
+    $buildkite_agent annotate --style error "Cannot get any version"
+
+    exit 1
+fi
+
+# release
+
+if [ "$GITHUB_TOKEN" = "" ]; then
+    echo "GITHUB_TOKEN token is not set"
+
+    $buildkite_agent annotate --style error "Cannot release version ${version} with GITHUB_TOKEN is not set"
+
+    exit 1
+fi
+
+export GITHUB_USER=$(echo "git@github.com:dxcn/oxy-dotnet-foundation.git" | cut -d: -f 2 | cut -d/ -f 1)
+export GITHUB_REPO=$(echo "$BUILDKITE_REPO" | cut -d: -f 2 | cut -d/ -f 2 | cut -d. -f 1)
+
+# TODO: use https://github.com/github-release/github-release instead when it support default github description behaviour
+release_payload=$(printf '{"tag_name": "%s","name": "%s","draft": false,"prerelease": false}' $version $version)
+release_result=$(curl -H "Authorization: token $GITHUB_TOKEN" --data "$release_payload" https://api.github.com/repos/$GITHUB_USER/$GITHUB_REPO/releases?access_token=$GITHUB_TOKEN)
+release_id=$(echo $release_result | jq -r .id)
+release_url=$(echo $release_result | jq -r .url)
+
+$buildkite_agent annotate --style info "Release $release_url"
+$buildkite_agent annotate --style success "Push version as release ${version} ($release_id)"
