fix hooks/command

diff --git a/hooks/command b/hooks/command
--- a/hooks/command
+++ b/hooks/command
@@ -29,6 +29,10 @@ dotnet_args="--rm -it $image /gitversion/GitVersion.dll /output json /nofetch /s
 version=$($docker run -v $(pwd):/src -w /src --entrypoint dotnet $dotnet_args)
 
 if [ "$version" = "" ]; then
+    $buildkite_agent annotate --style error "Cannot get any version"
+
+    exit 1    
+else
     $buildkite_agent meta-data set version $version
     $buildkite_agent annotate --style info "Using [$image] with GitVersion and SemVer"
     $buildkite_agent annotate --style success "Bump to version ${version}"
@@ -36,10 +40,6 @@ if [ "$version" = "" ]; then
     export VERSION=$version
 
     echo $version
-else
-    $buildkite_agent annotate --style error "Cannot get any version"
-
-    exit 1
 fi
 
 # release
